### ISSUE TITLE
fail on cold start

### ISSUE THREAD

**Issue by tomdavidson** [ahmetb/cloud-run-iap-terraform-demo#3]
How does this setup handle the cold start when Cloud Run can not start up fast enough?

**Comment by ahmetb** [comment]
IAP's authentication operates independently from the backend. So until the user is authenticated, Cloud Run is not invoked.

**Comment by ahmetb** [comment]
IAP's authentication operates independently from the backend. So until the user is authenticated, Cloud Run is not invoked.

**Comment by tomdavidson** [comment]
Thanks @ahmetb 

What are your thoughts on a warmup event that can prime the Cloud Run instance as the request is being authenticated? Perhaps a load balancer alert policy that triggers the Cloud Run service?

**Comment by ahmetb** [comment]
That's a product feature request. :) I recommend submitting it to Cloud Run issue tracker. https://cloud.google.com/support/docs/issue-trackers.

**Comment by tomdavidson** [comment]
OK, thought it would be a neat PR on this project. I wanted to gauge interest and to see if you had an idea on the delta with of the prime path going from lb -> log/alert policy -> pubsub -> cloud run

If Cloud Run is a valid notification channel on its own then pubsub can be removed but Im betting the log/alert is too slow to be helpful.

Looks like the LB can have a policy that mirrors traffic so the prime path could skip the log/alerting, but not sure how to make the container unaware and not have to handle the second path or port.

**Comment by ahmetb** [comment]
That's a quite neat idea —but complicates this repo. Feel free to make use of it yourself.

**Comment by ahmetb** [comment]
Also worth noting that LB logs are not realtime and have 10-30 seconds of delay based on my observation. Most times people will authenticate by then and hit Cloud Run already.
